server:
  address: localhost
  port: ${PORT:8080}
  
spring:
  application:
    name: KALAMBA
  
  # DB 설정
  datasource:
    url: jdbc:mysql://localhost:3306/kalamba
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      # create - 기존 테이블 삭제 후 다시 생성 (DROP + CREATE)
      # create-drop - create와 같으나 종료 시점에 테이블 DROP
      # update - 변경분만 반영 (운영DB에서 사용 X)
      # validate - 엔티티와 테이블이 정상 매핑되었는지만 확인
      # none - 사용하지 않음
    properties:
      hibernate:
        show_sql: true    # 터미널에 하이버네이트 실행 SQL을 출력
        format_sql: true    # 터미널에 출력되는 실행 SQL의 가독성 향상
        # use_sql_comments: true    # 추가 주석 표시

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace    # 하이버네이트 SQL 로그 중 '?'에 입력된 값 표시 

resource:
  api:
    key: ${API_AUTH_KEY:''}
  ASIA:
    baseURL: ${API_AUTH_ASIA_BASEURL:''}
  KR:
    baseURL: ${API_AUTH_KR_BASEURL:''}