server:
  address: localhost
  port: ${env.PORT:8080}
  
spring:
  application:
    name: KALAMBA

resource:
  api:
    key: ${env.API_AUTH_KEY:''}
  ASIA:
    baseURL: ${env.API_AUTH_ASIA_BASEURL:''}
  KR:
    baseURL: ${env.API_AUTH_KR_BASEURL:''}