server:
  address: localhost
  port: ${PORT:8080}
  
spring:
  application:
    name: KALAMBA

resource:
  api:
    key: ${API_AUTH_KEY:''}
  ASIA:
    baseURL: ${API_AUTH_ASIA_BASEURL:''}
  KR:
    baseURL: ${API_AUTH_KR_BASEURL:''}